name: Type Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true
  PUBLIC_API_URL: https://toottally.com/

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.14.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Run type checker
        run: pnpm run check
